---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - blead-thr
  - dev
  - dev-thr
  - 5.26.1
  - 5.26.1-thr
  - 5.24.2
  - 5.24.2-thr
  - 5.22.4
  - 5.22.4-thr
  - 5.20.3
  - 5.20.3-thr
  - 5.18.3
  - 5.18.3-thr
  - 5.16.3
  - 5.16.3-thr
  - 5.14.4
  - 5.14.4-thr
  - 5.12.5
  - 5.12.5-thr
  - 5.10.1
  - 5.10.1-thr
  - 5.8.8
  - 5.8.8-thr
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install ExtUtils::HasCompiler Module::Implementation
  - pushd /tmp
  - git clone git://github.com/houseabsolute/List-SomeUtils
  - pushd List-SomeUtils
  - git checkout $TRAVIS_BRANCH || git checkout master
  - perl Makefile.PL
  - make install
  - popd
  - popd
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - perl Makefile.PL
  - make
  - prove -b -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
